### ISSUE TITLE
Ensure TSL secure conection for the prod. service

### ISSUE THREAD

**Issue by mgcam** [wtsi-npg/npg_porch#2]
The production service will use TLS secured connections, otherwise our auth tokens will be sniffable

**Comment by nerdstrike** [comment]
Also work on daemonising

**Comment by nerdstrike** [comment]
Got a process written down for enabling https. Dev instance lacks maturity for now, e.g. no daemonising, not enough disk for long term logging

**Comment by nerdstrike** [comment]
Update: The Sanger certificate needs to be referenced by the client (because it is self-signed and needs additional trust). Conda-installed pythons do not get access to the certificate by default (whereas the old system python does).

**Comment by mgcam** [comment]
The certificate is signed by our own CA. This CA certificate in some cases has  to be explicitly supplied for the cli client and should be made available for the browser.
