### ISSUE TITLE
No shebang line in deploy_schema.py, but README expects one

### ISSUE THREAD

**Issue by kjsanger** [wtsi-npg/npg_porch#58]
Documentation and script don't match here:

https://github.com/wtsi-npg/npg_porch/blob/90a3fc5bf77e9ca966090a8f61320631f9380892/README.md?plain=1#L109

There's no shebang line in the script, so it can't be run as described (also isn't set as executable)

**Comment by nerdstrike** [comment]
Resolved by #63
