### ISSUE TITLE
Test that the task's created timestamp is set at creation time only

### ISSUE THREAD

**Issue by mgcam** [wtsi-npg/npg_porch#7]
.. and is not reset on updates

**Comment by nerdstrike** [comment]
Created a task:
`       5 |           1 | 8154ed4b4122dc3938031809f2b95cf09fc22423b5554acbe2c329d8be83cef9 | {"name": "thing1"}  | PENDING |        | 2022-02-23 14:55:23.684121`
Then updated the task:
`       5 |           1 | 8154ed4b4122dc3938031809f2b95cf09fc22423b5554acbe2c329d8be83cef9 | {"name": "thing1"}  | CLAIMED |        | 2022-02-23 14:55:23.684121`

As we can see, the timestamp remained the same.
