### ISSUE TITLE
Ensure that the pipelines/{pipeline_name} endpoint returns all versions of the pipeline

### ISSUE THREAD

**Issue by mgcam** [wtsi-npg/npg_porch#9]
If more that one version of the pipeline is available, a list of multiple pipeline models should be returned. Review the code and write unit tests.

**Comment by nerdstrike** [comment]
I think this is a non-issue with the current schema. Name is unique, therefore only one version is applicable to fetching by name.

**Comment by mgcam** [comment]
Yes, of course
